/* Northgate Order Flow — a WORKED EXAMPLE for the codebase-atlas skill.
   Northgate is a fictional online bookshop. Every path, line count and vendor below is
   invented, so that no real system is disclosed. When you build an atlas for a real
   repository, every one of these numbers must come from `wc -l` and every path must exist.
   Build it:  python3 ../scripts/build.py order-flow.data.js atlas.html ../themes/drafting.css */

const META={
  title:'Northgate Order Flow',
  name:'Northgate', tag:'Order Flow',
  run:'▶ FOLLOW ONE ORDER',
  stats:[['MOVING PARTS','#blocks'],['STEPS IN ONE ORDER','#steps'],
         ['LINES OF CODE BEHIND IT','41,200'],['ORDERS PER DAY','7,400']],
  legend:['TALLER = MORE CODE','LINE = A PATH AN ORDER TAKES','MOVING MARK = ONE ORDER'],
  chapters:[[0,'BROWSE'],[2,'CHECKOUT'],[5,'ORDER'],[7,'WAREHOUSE'],[9,'DELIVERY']],
  intro:{eyebrow:'THE WHOLE THING', h:'One order, end to end',
    p:['Somebody searches for a book, puts it in a basket and pays. Eighteen minutes later a picker in Leeds is holding it. The next morning it is on a doorstep.',
       'This map is the machinery between those moments. Every block is a real part of it.']},
  key:[['Taller block','more code inside it'],['Colour','which part of the business it serves'],
       ['Line on the floor','a path an order really takes'],['Moving mark','one order in flight']],
  movementsLabel:'THE FIVE MOVEMENTS',
  movements:[['Browse','find the book','search'],['Checkout','take the money','payments'],
             ['Order','commit the promise','orders'],['Warehouse','pick and pack it','wms'],
             ['Delivery','get it to the door','carrier']],
  cta:'Press <strong>FOLLOW ONE ORDER</strong> to watch one order cross the whole business.',
  done:'One parcel is on a van, the money is captured, the stock is decremented, and the customer has a tracking number. Eleven services agreed on all four.'
};

const G={
  storefront:{s:'SHOPFRONT', n:'What the customer sees', c:'#6F9BA8'},
  checkout:{s:'CHECKOUT',   n:'Taking the money',        c:'#C9A227'},
  orders:{s:'ORDER CORE',   n:'The promise we made',     c:'#C97B4B'},
  stock:{s:'WAREHOUSE',     n:'Moving real objects',     c:'#8CA36B'},
  delivery:{s:'DELIVERY',   n:'Getting it to the door',  c:'#8E86B8'},
  platform:{s:'THE SERVICE',n:'Running the business',    c:'#7D8A94'},
  records:{s:'RECORDS',     n:'What it remembers',       c:'#5E6E77'}
};

const N=[
 {id:'catalog',c:'C1',n:'Catalogue',g:'storefront',x:0,y:0,w:3,h:2,z:30,
  w1:'Every title we sell, with its price, its cover and whether it can be shipped today.',
  h1:'Read from a replica, cached at the edge for 60 seconds. Writes come from the publisher feed importer overnight.',
  f:[['catalog/models.py',420],['catalog/feed_import.py',680]],s:['Postgres replica','edge cache']},
 {id:'search',c:'C2',n:'Search',g:'storefront',x:0,y:3,w:3,h:2,z:34,
  w1:'Turns what somebody typed into books they might buy, including the spelling they got wrong.',
  h1:'An inverted index rebuilt nightly, with a typo-tolerant matcher in front. Ranking blends text relevance with stock on hand, so we do not sell what we cannot ship.',
  f:[['search/index.py',540],['search/rank.py',310]],s:['inverted index','typo tolerant']},
 {id:'cart',c:'C3',n:'Basket',g:'storefront',x:0,y:6,w:3,h:2,z:26,
  w1:'Holds what somebody intends to buy, for thirty days, whether or not they are signed in.',
  h1:'Keyed by a cookie until sign-in, then merged into the account basket. The merge is the fiddly part and has its own test suite.',
  f:[['cart/service.py',390],['cart/merge.py',180]],s:['cookie to account merge']},
 {id:'pricing',c:'K1',n:'Price & promotions',g:'checkout',x:4,y:0,w:3,h:2,z:28,
  w1:'Decides what the customer actually pays: the price, the discount code, the tax, the delivery fee.',
  h1:'A pure function over basket plus rules. No network calls, so it can be replayed against any past order to explain a charge.',
  f:[['pricing/engine.py',610],['pricing/rules.py',450]],s:['pure function','replayable']},
 {id:'checkout',c:'K2',n:'Checkout',g:'checkout',x:4,y:3,w:3,h:2,z:44,
  w1:'The four screens between a full basket and a paid order.',
  h1:'One state machine, one form per step, everything saved server side so a dropped phone does not lose the order.',
  f:[['checkout/flow.py',720],['checkout/forms.py',360]],s:['state machine','server-side draft']},
 {id:'fraud',c:'K3',n:'Risk check',g:'checkout',x:4,y:6,w:3,h:2,z:24,
  w1:'Scores an order before we take the money, and holds the ones that look wrong.',
  h1:'Rules plus a scoring model. Anything above the threshold goes to a review queue rather than being refused outright.',
  f:[['risk/score.py',280],['risk/queue.py',150]],s:['review queue','threshold']},
 {id:'payments',c:'K4',n:'Payments',g:'checkout',x:8,y:3,w:3,h:2,z:48,
  w1:'Authorises the card at checkout and captures the money only when the parcel leaves the building.',
  h1:'Authorise-then-capture against the payment provider, with webhooks for the asynchronous outcomes. Every webhook event id is recorded so a replay cannot charge twice.',
  f:[['payments/provider.py',520],['payments/webhooks.py',430]],s:['auth then capture','idempotent webhooks']},
 {id:'orders',c:'O1',n:'Order core',g:'orders',x:12,y:1,w:3,h:2,z:52,
  w1:'The promise we made to a customer, and the one record every other system agrees with.',
  h1:'One transaction creates the order, reserves the stock and writes the audit line. If any part fails, none of it happened.',
  f:[['orders/service.py',980],['orders/state.py',340]],s:['single transaction','source of truth']},
 {id:'inventory',c:'O2',n:'Stock',g:'orders',x:12,y:5,w:3,h:2,z:38,
  w1:'How many of each title we have, and how many are already promised to somebody else.',
  h1:'Reservations are separate from counts, so two customers cannot be sold the last copy. Reservations expire after twenty minutes if payment never lands.',
  f:[['inventory/reserve.py',470],['inventory/counts.py',260]],s:['reservation ledger','20 min expiry']},
 {id:'events',c:'O3',n:'Event stream',g:'orders',x:16,y:5,w:3,h:2,z:26,
  w1:'Announces that something happened, so that the rest of the business can react without being asked.',
  h1:'At-least-once delivery, so every consumer must be idempotent. Ordering is guaranteed per order id only.',
  f:[['events/bus.py',300],['events/consumers.py',410]],s:['at least once','per-key ordering']},
 {id:'wms',c:'W1',n:'Pick lists',g:'stock',x:16,y:1,w:3,h:2,z:46,
  w1:'Turns paid orders into a walking route through the warehouse, in the order the shelves appear.',
  h1:'Batches orders into waves, then sorts by aisle. A bad route costs minutes per pick, which is the largest controllable cost in the building.',
  f:[['warehouse/waves.py',640],['warehouse/route.py',380]],s:['wave batching','aisle order']},
 {id:'pack',c:'W2',n:'Packing',g:'stock',x:20,y:1,w:3,h:2,z:30,
  w1:'Chooses the box, confirms what is in it, and closes the order for picking.',
  h1:'Box choice is a bin-packing heuristic against the parcel bands the carriers charge by. One band saved per parcel is real money at this volume.',
  f:[['warehouse/pack.py',420]],s:['bin packing','carrier bands']},
 {id:'labels',c:'W3',n:'Labels',g:'stock',x:20,y:4,w:3,h:2,z:24,
  w1:'Prints the address label and the customs paperwork at the packing bench.',
  h1:'Talks to bench printers over a local queue. If the carrier API is down, labels fall back to a pre-allocated pool of tracking numbers.',
  f:[['labels/print.py',290],['labels/pool.py',160]],s:['printer queue','number pool']},
 {id:'carrier',c:'D1',n:'Carriers',g:'delivery',x:25,y:0,w:3,h:2,z:36,
  w1:'Hands the parcel to whoever is delivering it, and books the collection.',
  h1:'Four carriers behind one interface, chosen per parcel by destination, weight and cut-off time. Adding a fifth must be a config change, never a rewrite.',
  f:[['carriers/base.py',210],['carriers/royalmail.py',330],['carriers/dpd.py',310]],s:['abstract carrier','cut-off aware']},
 {id:'tracking',c:'D2',n:'Tracking',g:'delivery',x:29,y:0,w:3,h:2,z:28,
  w1:'Follows the parcel after it leaves us and notices when it stops moving.',
  h1:'Polls carrier scans and normalises four vocabularies into one. An alert fires on silence, not only on a failure scan.',
  f:[['tracking/poll.py',350],['tracking/normalise.py',240]],s:['normalised scans','alert on silence']},
 {id:'notify',c:'D3',n:'Customer mail',g:'delivery',x:32,y:0,w:3,h:2,z:24,
  w1:'The four emails a customer actually wants: paid, packed, posted, delivered.',
  h1:'Templated, queued, and deduplicated per order and per type. A retry storm must never send the same mail twice.',
  f:[['notify/mailer.py',280],['notify/templates.py',190]],s:['queued','deduplicated']},
 {id:'returns',c:'D4',n:'Returns',g:'delivery',x:25,y:4,w:3,h:2,z:26,
  w1:'Takes a book back, refunds the money and puts the stock back on the shelf.',
  h1:'Refund and restock are separate steps with separate failure modes. Restocking a damaged copy is the mistake that costs twice.',
  f:[['returns/service.py',400],['returns/restock.py',220]],s:['refund','restock','grading']},
 {id:'web',c:'P1',n:'Website',g:'platform',x:12,y:11,w:3,h:2,z:40,
  w1:'The shop itself: pages, sessions, and everything a customer can click.',
  h1:'Server-rendered pages with islands of client code. Rendering budget is 200 ms at the 95th percentile, enforced in CI.',
  f:[['web/app.py',870],['web/pages/',1200]],s:['server rendered','p95 budget']},
 {id:'auth',c:'P2',n:'Accounts',g:'platform',x:8,y:11,w:3,h:2,z:24,
  w1:'Sign-in, sessions and the address book.',
  h1:'Sessions in a signed cookie, addresses validated against a postcode service on save rather than at checkout.',
  f:[['accounts/auth.py',330],['accounts/addresses.py',260]],s:['signed cookies','address validation']},
 {id:'admin',c:'P3',n:'Back office',g:'platform',x:16,y:11,w:3,h:2,z:30,
  w1:'Where staff fix the orders that went wrong, and the only place money can be moved by hand.',
  h1:'Every action is attributed and logged. Refunds above a threshold need a second pair of eyes.',
  f:[['admin/views.py',720],['admin/audit.py',210]],s:['attributed actions','two-person rule']},
 {id:'jobs',c:'P4',n:'Background work',g:'platform',x:20,y:11,w:3,h:2,z:36,
  w1:'Everything that must happen without a customer waiting: imports, retries, nightly reconciliation.',
  h1:'A queue with per-task retry policy. Anything that touches money reconciles nightly against the provider, and mismatches page a human.',
  f:[['jobs/worker.py',480],['jobs/schedule.py',300]],s:['retry policy','nightly reconcile']},
 {id:'api',c:'P5',n:'Partner API',g:'platform',x:24,y:11,w:3,h:2,z:32,
  w1:'How schools and libraries place bulk orders without touching the website.',
  h1:'Versioned and rate limited. Bulk orders bypass the basket but never the risk check.',
  f:[['api/v2/routes.py',560],['api/limits.py',170]],s:['versioned','rate limited']},
 {id:'support',c:'P6',n:'Support tools',g:'platform',x:8,y:14,w:3,h:2,z:22,
  w1:'Lets an agent see the same order the customer is describing on the phone.',
  h1:'Read-only views over the order timeline. Any change goes through the back office, so support cannot silently mutate an order.',
  f:[['support/timeline.py',290]],s:['read only','order timeline']},
 {id:'db',c:'R1',n:'Database',g:'records',x:28,y:12,w:3,h:2,z:44,
  w1:'Orders, payments, stock movements, customers. The business, written down.',
  h1:'One primary, two replicas. Reads that can tolerate a second of staleness go to a replica; anything that decides money does not.',
  f:[['db/models.py',1400],['db/migrations/',2100]],s:['primary + replicas','read routing']},
 {id:'audit',c:'R2',n:'Audit log',g:'records',x:32,y:8,w:3,h:2,z:20,
  w1:'Who changed what, when, and what it looked like before.',
  h1:'Append only, written in the same transaction as the change. If the audit write fails, the change fails.',
  f:[['audit/log.py',240]],s:['append only','same transaction']},
 {id:'metrics',c:'R3',n:'Measurements',g:'records',x:32,y:11,w:3,h:2,z:20,
  w1:'Orders per hour, picks per hour, parcels missed. The numbers the morning meeting runs on.',
  h1:'Alerts fire on missing expected output, not only on errors. A quiet warehouse at 10am is the signal that matters.',
  f:[['metrics/collect.py',260]],s:['alert on absence']}
];

const COPY={
 catalog:['CATALOGUE','Every title we sell, and whether it can ship today',
   'A wrong stock flag here sells a book we cannot send, which costs a refund and a customer.',
   'The shop shows stale prices and availability. Orders arrive that cannot be filled.'],
 search:['SEARCH','Turns what somebody typed into books they might buy',
   'Most sessions start here. Ranking that ignores stock sells what we cannot ship.',
   'Customers cannot find books they would have bought. Revenue falls with no error anywhere.'],
 cart:['BASKET','Holds what somebody intends to buy, for thirty days',
   'It is the memory of an intention. Losing it loses the sale outright.',
   'Baskets empty on sign-in. The complaint arrives before the metric does.'],
 pricing:['PRICING','Decides what the customer actually pays',
   'It is the number on the card statement. Being wrong here is a refund and an apology.',
   'Customers are charged the wrong amount, and we cannot explain why afterwards.'],
 checkout:['CHECKOUT','The four screens between a full basket and a paid order',
   'Every abandoned step is money already earned and then dropped.',
   'Nobody can buy anything. The most expensive outage in the business.'],
 fraud:['RISK','Scores an order before we take the money',
   'Too strict and we refuse good customers; too loose and we ship to fraud. Both are visible in the same week.',
   'Either fraudulent orders ship, or genuine customers are turned away silently.'],
 payments:['PAYMENTS','Authorises at checkout, captures when it ships',
   'Money only moves when a parcel does. That is what makes cancellations cheap.',
   'Orders are taken but never charged, or charged twice. Both need manual repair.'],
 orders:['ORDERS','The promise we made, and the one record all systems agree with',
   'Every other system defers to this one. When it disagrees with itself, nothing downstream can be trusted.',
   'The business stops. Nothing can be created, picked, refunded or answered.'],
 inventory:['STOCK','How many we have, and how many are already promised',
   'Reservations are what stop two people buying the last copy.',
   'We oversell. Somebody in the warehouse discovers it, hours after the customer was thanked.'],
 events:['EVENTS','Announces that something happened',
   'It lets parts of the business react without knowing about each other.',
   'Downstream work stops quietly. Orders are paid and nothing follows.'],
 wms:['PICK LISTS','Turns paid orders into a route through the warehouse',
   'Picking time is the largest controllable cost in the building. The route is the lever.',
   'The floor has nothing to pick. Parcels miss the evening collection.'],
 pack:['PACKING','Chooses the box and confirms what is in it',
   'Box choice sets the carrier price band. One band per parcel is real money at this volume.',
   'Picked orders pile up unpacked. Everything upstream keeps working, which hides it.'],
 labels:['LABELS','Prints the address label at the bench',
   'A bench without labels is a bench that has stopped.',
   'Packing halts. The pre-allocated number pool buys about two hours.'],
 carrier:['CARRIERS','Hands the parcel to whoever is delivering it',
   'Cut-off times are promises. Missing one moves every parcel a day later.',
   'Parcels are packed and go nowhere. The customer sees a promise we already broke.'],
 tracking:['TRACKING','Follows the parcel and notices when it stops',
   'Most support contacts are about a parcel nobody is watching.',
   'We learn about lost parcels from the customer, which is the expensive way.'],
 notify:['MAIL','The four emails a customer actually wants',
   'Silence after payment reads as a failed order, and generates a support call each time.',
   'Customers are not told anything. Support volume doubles within a day.'],
 returns:['RETURNS','Takes it back, refunds it, restocks it',
   'A return handled well is usually a second sale. Handled badly it is a chargeback.',
   'Refunds stall and stock stays off the shelf while we still hold the book.'],
 web:['WEBSITE','The shop itself, pages and sessions',
   'It is the whole storefront. Slow pages cost orders in direct proportion.',
   'No shop. Partner orders through the API keep working, which is a thin comfort.'],
 auth:['ACCOUNTS','Sign-in, sessions and the address book',
   'A bad address is a parcel delivered to nobody, paid for twice.',
   'Nobody can sign in. Guest checkout carries what it can.'],
 admin:['BACK OFFICE','Where staff fix the orders that went wrong',
   'It is the only place money moves by hand, so it is the only place to watch closely.',
   'Broken orders cannot be repaired. They queue up and become refunds.'],
 jobs:['WORKERS','Everything that happens with nobody waiting',
   'Nightly reconciliation is how we learn the ledger and the provider disagree.',
   'Retries stop and mismatches go unnoticed until an accountant finds them.'],
 api:['PARTNER API','Bulk orders without touching the website',
   'Schools and libraries order in hundreds. One outage here is a quarter of a day of volume.',
   'Bulk customers cannot order and will phone somebody who can take it manually.'],
 support:['SUPPORT','Shows the agent the order the customer is describing',
   'Being able to see the same screen ends most calls in a minute.',
   'Agents guess. Handling time doubles and confidence drops.'],
 db:['DATABASE','Orders, payments, stock, customers',
   'The business written down. Everything else is derived from it.',
   'Everything stops. This is the failure that has no partial version.'],
 audit:['AUDIT','Who changed what, and what it looked like before',
   'It is how a disputed charge gets answered with a fact instead of an opinion.',
   'Disputes become unanswerable, and manual corrections cannot be traced.'],
 metrics:['MEASURE','Orders, picks and misses per hour',
   'Alerting on absence is what catches a quiet warehouse before the customers do.',
   'Failures stay quiet until the morning meeting, which is eight hours too late.']
};

const E=[
 ['web','catalog',0],['catalog','search',0],['search','cart',1],['cart','checkout',1],
 ['pricing','checkout',0],['cart','pricing',0],['checkout','fraud',1],['fraud','payments',1],
 ['payments','orders',1],['orders','inventory',1],['inventory','wms',1],['orders','events',0],
 ['events','jobs',0],['wms','pack',1],['labels','pack',0],['pack','carrier',1],
 ['carrier','tracking',1],['tracking','notify',1],['returns','inventory',0],['orders','db',0],
 ['db','admin',0],['auth','web',0],['api','orders',0],['jobs','notify',0],['support','orders',0],
 ['orders','audit',0],['payments','audit',0],['metrics','db',0],['admin','wms',0],['jobs','payments',0]
];

const STEPS=[
 ['search','Ten past eight in the evening. Somebody searches for a book, spelling the author wrong.',null],
 ['cart','It goes in the basket. Nobody has signed in yet, so the basket belongs to a cookie.',['search','cart']],
 ['checkout','Sign-in merges the basket into the account, and the four checkout screens begin.',['cart','checkout']],
 ['fraud','Before any money moves, the order is scored. This one is well under the threshold.',['checkout','fraud']],
 ['payments','The card is authorised, not captured. We have permission to take the money, and have not taken it.',['fraud','payments']],
 ['orders','One transaction creates the order, reserves the stock and writes the audit line. All three, or none.',['payments','orders']],
 ['inventory','The last two copies are now promised. Nobody else can be sold them.',['orders','inventory']],
 ['wms','Overnight, the order joins a wave and becomes a walking route through the aisles in Leeds.',['inventory','wms']],
 ['pack','A picker scans it at the bench. The box is chosen to stay inside the cheaper carrier band.',['wms','pack']],
 ['carrier','Weight and postcode choose the carrier. The collection is booked before the evening cut-off.',['pack','carrier']],
 ['tracking','A tracking number comes back and the parcel starts being watched for silence.',['carrier','tracking']],
 ['notify','The customer is told it is on the way, and the money is captured at last.',['tracking','notify']]
];
